# Generated by Django 5.0 on 2023-12-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0002_alter_worker_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
    ]
